version: '3.1'

services:

  postgres:
    container_name: eventflix-idp-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: eventflix
      POSTGRES_PASSWORD: eventflix
    ports:
      - 5401:5432
